### ISSUE TITLE
API printf 형식

### ISSUE THREAD

**Issue by mojunsang26** [kosslab-kr/Tizen-NN-Runtime#11]
printf("nnfw/your/path/filename.cc  -----> function name     start /n");
printf("nnfw/your/path/filename.cc  -----> function name     return /n");

**Comment by timedilation** [comment]
for return :
printf("nnfw/your/path/filename.cc -----> function name return [errorname] /n");

ex)
printf("nnfw/runtimes/neurun/src/frontend/compilation.cc  -----> ANeuralNetworksCompilation_finish return UNEXPECTED_NULL /n");

**Comment by timedilation** [comment]
#define DEBUG 1
#define debug_print(args ...) if (DEBUG) fprintf(stderr, args)
