### ISSUE TITLE
새로운 프로젝트 Build 시 에러

### ISSUE THREAD

**Issue by lazineer** [kosslab-kr/Tizen-NN-Runtime#25]
lazineer@ubuntu:~/Tizen-NN-Runtime/Camera$ sudo gbs build --include-all -A armv7l
info: generate repositories ...
warning: No local package repository for arch armv7l
info: build conf has been downloaded at:
      /var/tmp/root-gbs/tizen.conf
info: start building packages from: /home/lazineer/Tizen-NN-Runtime/Camera (git)
2018-10-21 02:27 -0700
gbs 0.25.4
info: prepare sources...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
info: start export source from: /home/lazineer/Tizen-NN-Runtime/Camera ...
info: the following untracked files would be included:
   .cproject
   .exportMap
   .project
   .settings/
   .tproject
   CMakeLists.txt
   Debug/
   inc/
   packaging/
   shared/
   src/
   tizen-manifest.xml
info: Creating (native) source archive Camera-0.0.1.tar.gz from '739047a866d920a0a56ca8f02a2567ad02da3e32'
error: Git command failed: Can't describe HEAD. Git error: fatal: Not a valid object name HEAD
error: <gbs>Failed to export packaging files from git tree
info: retrieving repo metadata...
info: parsing package data...
info: building repo metadata ...
info: resolving skipped packages ...
info: package dependency resolving ...
warning: no available packages to build.
info: *** Build Status Summary ***
=== Total succeeded built packages: (0) ===
info: generated html format report:
     /home/lazineer/buildroot_tizen/local/repos/tizen/armv7l/index.html
info: generated RPM packages can be found from local repo:
     /home/lazineer/buildroot_tizen/local/repos/tizen/armv7l/RPMS
info: generated source RPM packages can be found from local repo:
     /home/lazineer/buildroot_tizen/local/repos/tizen/armv7l/SRPMS
info: build logs can be found in:
     /home/lazineer/buildroot_tizen/local/repos/tizen/armv7l/logs
info: build roots located in:
     /home/lazineer/buildroot_tizen/local/BUILD-ROOTS/scratch.armv7l.*
error: <gbs>some packages failed to be built

**Comment by timedilation** [comment]
해당 폴더 안에서 아래의 커맨드를 실행시킴으로써 해결됨
```
git init
git add *
git commit -m "something"
```
