### ISSUE TITLE
파이썬이 타이젠에서 동작하나요?

### ISSUE THREAD

**Issue by mojunsang26** [kosslab-kr/Tizen-NN-Runtime#3]
파이썬이 타이젠에서 동작하는지 궁금합니다.

**Comment by eksson** [comment]
Tizen 5.0 이미지에는 파이썬이 포함되어서 이미지가 발행되고 있습니다.
Tizen 5.0 이미지를 다운 받아서 사용하신다면 파이썬을 사용할 수 있을 겁니다.
