### ISSUE TITLE
Tensorflow-lite가 tizen 5.0 이미지에 들어가 있나요?

### ISSUE THREAD

**Issue by mojunsang26** [kosslab-kr/Tizen-NN-Runtime#4]
Tensorflow-lite가 tizen 5.0 이미지에 들어가 있는지 궁금합니다^^

**Comment by eksson** [comment]
Tensorflow-lite 는 Tizen 에서 빌드는 됩니다만, 발행되는 이미지에 포함되어 있지는 않습니다.
https://git.tizen.org/cgit/platform/upstream/tensorflow/
https://review.tizen.org/gerrit/#/admin/projects/platform/upstream/tensorflow/
소스코드를 다운받으셔서 빌드하셔서 사용하셔야 할 것 같네요.
