### ISSUE TITLE
호스트 컴퓨터 우분투 버전

### ISSUE THREAD

**Issue by timedilation** [kosslab-kr/Tizen-NN-Runtime#5]
다들 버전 몇을 사용하고 계시는지, 어떤것을 사용하면 좋을지 궁금합니다.

**Comment by mojunsang26** [comment]
전 16.04 사용하고 있습니다.
개발자 사이트의 Getting started guide 보시면 우분투는 16.04까지 지원되는 것으로 나와있습니다.
18.04에서 apt sources.list에 16.04버전 repo url을 추가해서 진행했을 때 tizen gerrit ssh 접근이 되지 않았습니다.

**Comment by eksson** [comment]
Tizen Platform 은 우분투 16.04 베이스에서 개발 및 테스트 되고 있습니다.
그 상위 버전은 지원 계획이지만, 아직은 16.04 버전을 권해 드립니다.

**Comment by timedilation** [comment]
넵 16.04로 작업하겠습니다.
