### ISSUE TITLE
xor.cpp 컴파일 에러

### ISSUE THREAD

**Issue by timedilation** [kosslab-kr/Tizen-NN-Runtime#8]
```root@localhost:/home# g++ -std=c++11 xor.cpp -ltensorflow-lite -ldl -pthread
/usr/lib/gcc/armv7l-tizen-linux-gnueabi/4.9/../../../libtensorflow-lite.a(conv.o):
In function 'tflite::multithreaded_ops::GetThreadPoolDevice()':
(.text+0xbe4): undefined reference to 'std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())' /usr/lib/gcc/armv7l-tizen-linux-gnueabi/4.9/../../../libtensorflow-lite.a(conv.o): In function 'std::thread::_State_impl<std::_Bind_simple<std::function<void ()> ()> >::~_State_impl()' 
(.text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEED2Ev[_ZNSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEED5Ev]+0x1e): undefined reference to 'std::thread::_State::~_State()'
/usr/lib/gcc/armv7l-tizen-linux-gnueabi/4.9/../../../libtensorflow-lite.a(conv.o): In function 'std::thread::_State_impl<std::_Bind_simple<std::function<void ()> ()> >::~_State_impl()': 
(.text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEED0Ev[_ZNSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEED5Ev]+0x1e): undefined reference to 'std::thread::_State::~_State()'
/usr/lib/gcc/armv7l-tizen-linux-gnueabi/4.9/../../../libtensorflow-lite.a(conv.o):
(.data.rel.ro._ZTINSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEEE[_ZTINSt6thread11_State_implISt12_Bind_simpleIFSt8functionIFvvEEvEEEE]+0x8):
undefined reference to 'typeinfo for std::thread::_State' /usr/lib/gcc/armv7l-tizen-linux-gnueabi/4.9/../../../libtensorflow-lite.a(op_resolver.o): In function 'void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .isra.41]':
(.text+0x42): undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned int&, unsigned int)'
collect2: error: ld returned 1 exit status```

설치한 패키지들 사이의 버전 문제가 있는 것 같습니다. 아직 해결하지 못하였습니다.

**Comment by eksson** [comment]
PC에서 GBS 로 빌드를 할 수 있네요.
Ubuntu 에서 Tizen Studio 를 설치하시고
오른쪽 위에 보시면 "Open Perspective" 아이콘을 누르시고
"Platform"을 추가해 주세요.
그러면 Tizen Studio에서 Platform 프로젝트를 개발할 수 있네요.

먼저 기본 템플릿 "Helloworld" 프로젝트 만드시고
Helloworld.c 파일을 cpp 파일로 rename 하고
xor 소스코드를 복사하고 붙혀넣기 하고 저장하세요.

그 상태에서 Tizen Studio 로 바로 빌드를 하면 2.4 mobile 용으로 빌드를 하네요.
그래서, Tizen Studio 를 종료하고
터미널 창에서 tizen 5.0 용으로 빌드를 하니까 rpm 파일이 만들어지네요.

cpec 파일과 CMake 도 기본으로 만들어 주네요.

**Comment by lazineer** [comment]
기본 템플릿 프로젝트 만드시고 Properties 수정 없이 빌드하신건가요?
파일 확장자는 cpp로 바꿨는데 <string>, <vector> include가 안 되네요
그리고 CMake 파일에서 소스파일 이름을 바꾸라고 하셨는데, 타이젠 스튜디오 상에서 CMake와 관련된 메뉴가 있는건가요?

**Comment by eksson** [comment]
템플릿을 어떻게 만드셨나요? Platform 프로젝트 템플릿으로 만드셔야 하는데,
Tizen Studio 창 오른쪽 위에 보시며 Perspective 아이콘이 있고, "+" 아이콘 누르시면 Platform 을 추가할 수 있습니다.
만약 Platform 이 보이지 않는다면, Package Manager 에서 Platform IDE 가 찾아서 설치하시면 됩니다.
Platform 이 선택된 상태에서 템플릿 만드시면 되구요.
파일 이름은 어떻게 바꾸셨나요? Tizen Studio 화면에서 파일이름에서 마우스 오른쪽 버튼 누르고
rename 선택하셔서 수정을 하시면 되구요.
CMake 내용은 수정을 안해도 빌드가 되었던 것 같은데, 그래도 확실히 하기 위해서는
이름 바꾼 파일을 반영해 주셔야겠죠.
마찮가지로 Tizen Studio 화면에서 CMake 파일 선택하시면 내용 보실 수 있고, 바로 수정하시면 됩니다.
저는 그런 상태에서 빌드를 했습니다.

**Comment by lazineer** [comment]
Tizen Studio에서 프로젝트 생성 시 Project Explorer의 "Create new project"를 선택하는게 아니라,  File 메뉴 혹은 File 메뉴 바로 밑의 아이콘을 선택하여 생성하면 손수석님이 말씀하신 프로젝트 생성이 가능하네요 ^^;;
![new_project](https://user-images.githubusercontent.com/4532012/46354110-cbb89380-c698-11e8-9bce-86a725307d95.png)
